### ISSUE TITLE
Use new Pravega API

### ISSUE THREAD

**Issue by RaulGracia** [pravega/hadoop-connectors#106]
**Problem description**
As part of pravega/pravega#3126, the use of ClientFactory and other client-related APIs was deprecated. In PR pravega/pravega#4417 we are removing all these deprecated APIs, which means that if you are using them your application won't compile. We need to update the samples to use the proper Pravega API.

**Problem location**
Use of Pravega API.

**Suggestions for an improvement**
Use the right APIs.

**Comment by crazyzhou** [comment]
Re-checked all removed APIs are not used.
