### ISSUE TITLE
Prepare for 0.7 release

### ISSUE THREAD

**Issue by crazyzhou** [pravega/hadoop-connectors#124]
**Problem description**
As part of preparing for `0.7.0` release, update the following configurations from `gradle.properties`

- bump Pravega version to `0.7.0`
- change connection version to `0.7.0` from `0.7.0-SNAPSHOT`
- update Pravega sub-module commit

**Problem location**
`gradle.properties` and git pravega submodule

**Suggestions for an improvement**

**Comment by RaulGracia** [comment]
Closed via #125.
