### ISSUE TITLE
feature: add support for streamcut

### ISSUE THREAD

**Issue by yangb8** [pravega/hadoop-connectors#16]
currently, connector can only read all of events for streams. need to support reading part of events after PR https://github.com/pravega/pravega/pull/2337 is merged

**Comment by yangb8** [comment]
potential code change outline

# In PravegaInputFormat.java
need to call client.getSegments(stream, fromStreamCut, toStreamCut) or a better API like client.getSegments(stream, startime, endtime) to get Segments in required time window.

# In PravegaInputRecordReader.java
still client.readSegment() to get SegmentIterator, but the parameter is changed from Segment to SegmentRange

# In PravegaInputSplit.java
Actually, it's simpler, its members segment/startoffset/endoffset matches SegmentRanage perfectly.

# majority of this work will be about adding related unit/integrated tests

**Comment by yangb8** [comment]
add some key points after chatting with Sandeep

For hadoop-connectors, when calling client.getSegments(stream, fromStreamCut, endStreamCut) to get list of SegmentRanges, there are several options.

1. both fromStreamCut and endStreamCut are null, the behavior is the same as before that connectors will read all events out.

2. neither fromStreamCut nor endStreamCut is null. connectors just read events from SegmentRanges between the 2 cuts. However, the question is how to get `fromStreamCut` and `toStreamCut`. 

    Need to leverage StreamingClient:ReaderGroup.getStreamCuts() to get them. However, this part of logic must be in application which uses connectors but not connectors itself.

    the most common use case should be the end user retrieves latest StreamCut and then call hadoop-connectors with previous StreamCut as fromStreamCut and current latest StreamCut as toStreamCut.  To continue from failure point, application shall save StreamCut to persistent storage.

3. either fromStreamCut or endStreamCut is null, just the simplified cases of option 2

**Comment by shrids** [comment]
Updates based on the current state of discussions. (@yangb8 let me know if any point needs to be added).

```
The basic flow is: `get start/end StreamCut` -> `save endStreamCut as startStreamCut next round` -> `set MR job` -> `InputFormat gets SegmentRanges between start/endStreamCut` -> `generate Split per SegmentRange` -> `MR job: process events in each Split`
```

With the current BatchClient API this can be implemented as follows.
```
1. StreamSegmentsIterator ssItr = batchClient.getSegments(stream, startStreamCut, null); // read upto the current TAIL of the stream.
2. StreamCut sc = ssItr.getEndStreamCut(); // this is the current endStreamCut upto which segments are obtained.
//Persist it for the next Batch job, where it can be used as the starting stream cut..
3. MR Job: Process events for every SegmentRange obtained via ssltr.getIterator().

Repeat steps 1 to 3 with with `sc` as the starting stream cut for the next batch job.
```

**Comment by yangb8** [comment]
PR #22 is resolved
