### ISSUE TITLE
Add DCO plugin

### ISSUE THREAD

**Issue by fpj** [pravega/hadoop-connectors#17]
We need to add the plugin to enforce DCO sign-offs.

https://github.com/probot/dco

**Comment by yangb8** [comment]
@fpj 
I verified the setting in my forked repo, everything is working fine. However, seems like only owner can install DCO for target repository, so could you please add pravega/hadoop-connectors to DCO?

login as pravega user -> settings --> applications --> DCO configure --> Only select repositories --> search and add pravega/hadoop-connectors.  thanks
