### ISSUE TITLE
Update pravega snapshot version to latest from jcenter

### ISSUE THREAD

**Issue by vijikarthi** [pravega/hadoop-connectors#36]
- The pravega version is still pointing to 0.3.0-SNAPSHOT instead of latest published snapshot version from jcenter repo https://github.com/pravega/hadoop-connectors/blob/master/gradle.properties#L19

- Also, the pravega submodule needs to be updated to the corresponding snapshot commit

**Comment by yangb8** [comment]
PR #37 is merged.
