### ISSUE TITLE
Treat Pravega as a source dependency

### ISSUE THREAD

**Issue by EronWright** [pravega/hadoop-connectors#6]
**Problem description**
Fix the travis build of the connector to build Pravega automatically, so that the connector may be unit tested by travis.

**Suggestions for an improvement**
Consider using a submodule plus a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) to incorporate the Pravega build into the connector build.   See pravega/flink-connectors#88 for a similar issue.

**Comment by yangb8** [comment]
PR #7 has been merged
